// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	block.proto
	message.proto
	transaction.proto

It has these top-level messages:
	BlockHeader
	Block
	GetBlocksMsg
	GetInvMsg
	OnBlockMsg
	OnTransactionMsg
	GetDataMsg
	ContractSpec
	TxHeader
	Transaction
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockHeader struct {
	PreviousHash  string `protobuf:"bytes,1,opt,name=previousHash" json:"previousHash,omitempty"`
	StateHash     string `protobuf:"bytes,2,opt,name=stateHash" json:"stateHash,omitempty"`
	TimeStamp     uint32 `protobuf:"varint,3,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Nonce         uint32 `protobuf:"varint,4,opt,name=nonce" json:"nonce,omitempty"`
	TxsMerkleHash string `protobuf:"bytes,5,opt,name=txsMerkleHash" json:"txsMerkleHash,omitempty"`
	Height        uint32 `protobuf:"varint,6,opt,name=height" json:"height,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto1.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BlockHeader) GetPreviousHash() string {
	if m != nil {
		return m.PreviousHash
	}
	return ""
}

func (m *BlockHeader) GetStateHash() string {
	if m != nil {
		return m.StateHash
	}
	return ""
}

func (m *BlockHeader) GetTimeStamp() uint32 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *BlockHeader) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTxsMerkleHash() string {
	if m != nil {
		return m.TxsMerkleHash
	}
	return ""
}

func (m *BlockHeader) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Block struct {
	Header       *BlockHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto1.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto1.RegisterType((*BlockHeader)(nil), "proto.BlockHeader")
	proto1.RegisterType((*Block)(nil), "proto.Block")
}

func init() { proto1.RegisterFile("block.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x6b, 0x02, 0x9d, 0xb4, 0x07, 0x07, 0x91, 0x45, 0x3c, 0x84, 0xe0, 0xa1, 0x78,
	0xe8, 0x41, 0xc1, 0x07, 0xf0, 0xd4, 0x8b, 0x97, 0xe8, 0x0b, 0x6c, 0xe3, 0x60, 0x96, 0xb4, 0xbb,
	0x61, 0x77, 0x14, 0x5f, 0xcf, 0x37, 0x93, 0x9d, 0x0d, 0x24, 0x39, 0x2d, 0xf3, 0xff, 0xdf, 0xfc,
	0xec, 0x3f, 0x50, 0x9e, 0xce, 0xae, 0xed, 0x0f, 0x83, 0x77, 0xec, 0x30, 0x97, 0xe7, 0xee, 0x9a,
	0xbd, 0xb6, 0x41, 0xb7, 0x6c, 0x9c, 0x4d, 0x4e, 0xfd, 0x97, 0x41, 0xf9, 0x1a, 0xc9, 0x23, 0xe9,
	0x4f, 0xf2, 0x58, 0xc3, 0x76, 0xf0, 0xf4, 0x63, 0xdc, 0x77, 0x38, 0xea, 0xd0, 0xa9, 0xac, 0xca,
	0xf6, 0x9b, 0x66, 0xa1, 0xe1, 0x3d, 0x6c, 0x02, 0x6b, 0x26, 0x01, 0x56, 0x02, 0x4c, 0x42, 0x74,
	0xd9, 0x5c, 0xe8, 0x9d, 0xf5, 0x65, 0x50, 0xeb, 0x2a, 0xdb, 0xef, 0x9a, 0x49, 0xc0, 0x1b, 0xc8,
	0xad, 0xb3, 0x2d, 0xa9, 0x2b, 0x71, 0xd2, 0x80, 0x0f, 0xb0, 0xe3, 0xdf, 0xf0, 0x46, 0xbe, 0x3f,
	0xa7, 0xd4, 0x5c, 0x52, 0x97, 0x22, 0xde, 0x42, 0xd1, 0x91, 0xf9, 0xea, 0x58, 0x15, 0xb2, 0x3c,
	0x4e, 0x75, 0x0f, 0xb9, 0x54, 0xc0, 0xc7, 0x08, 0xc4, 0x1a, 0xf2, 0xed, 0xf2, 0x09, 0x53, 0xc9,
	0xc3, 0xac, 0x60, 0x33, 0x12, 0xf8, 0x02, 0xdb, 0xd9, 0x35, 0x82, 0x5a, 0x55, 0xeb, 0xd9, 0xc6,
	0xc7, 0x64, 0x35, 0x0b, 0xee, 0x54, 0x08, 0xf0, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xeb,
	0x81, 0xec, 0x60, 0x01, 0x00, 0x00,
}
