// Code generated by protoc-gen-go.
// source: transaction.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TransactionType int32

const (
	TransactionType_Issue           TransactionType = 0
	TransactionType_IssueUpdate     TransactionType = 1
	TransactionType_Atomic          TransactionType = 2
	TransactionType_JSContractInit  TransactionType = 3
	TransactionType_LuaContractInit TransactionType = 4
	TransactionType_ContractInvoke  TransactionType = 5
	TransactionType_ContractQuery   TransactionType = 6
)

var TransactionType_name = map[int32]string{
	0: "Issue",
	1: "IssueUpdate",
	2: "Atomic",
	3: "JSContractInit",
	4: "LuaContractInit",
	5: "ContractInvoke",
	6: "ContractQuery",
}
var TransactionType_value = map[string]int32{
	"Issue":           0,
	"IssueUpdate":     1,
	"Atomic":          2,
	"JSContractInit":  3,
	"LuaContractInit": 4,
	"ContractInvoke":  5,
	"ContractQuery":   6,
}

func (x TransactionType) String() string {
	return proto1.EnumName(TransactionType_name, int32(x))
}
func (TransactionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type OutPoint struct {
	TxHash []byte `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Index  uint32 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *OutPoint) Reset()                    { *m = OutPoint{} }
func (m *OutPoint) String() string            { return proto1.CompactTextString(m) }
func (*OutPoint) ProtoMessage()               {}
func (*OutPoint) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *OutPoint) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *OutPoint) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type TxIn struct {
	PrevOutPoint *OutPoint `protobuf:"bytes,1,opt,name=prevOutPoint" json:"prevOutPoint,omitempty"`
	TxWitness    []byte    `protobuf:"bytes,2,opt,name=txWitness,proto3" json:"txWitness,omitempty"`
}

func (m *TxIn) Reset()                    { *m = TxIn{} }
func (m *TxIn) String() string            { return proto1.CompactTextString(m) }
func (*TxIn) ProtoMessage()               {}
func (*TxIn) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *TxIn) GetPrevOutPoint() *OutPoint {
	if m != nil {
		return m.PrevOutPoint
	}
	return nil
}

func (m *TxIn) GetTxWitness() []byte {
	if m != nil {
		return m.TxWitness
	}
	return nil
}

type TxOut struct {
	Value int64  `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Addr  []byte `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (m *TxOut) Reset()                    { *m = TxOut{} }
func (m *TxOut) String() string            { return proto1.CompactTextString(m) }
func (*TxOut) ProtoMessage()               {}
func (*TxOut) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *TxOut) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TxOut) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

type ContractSpec struct {
	Addr   []byte   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Code   []byte   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Params []string `protobuf:"bytes,3,rep,name=params" json:"params,omitempty"`
}

func (m *ContractSpec) Reset()                    { *m = ContractSpec{} }
func (m *ContractSpec) String() string            { return proto1.CompactTextString(m) }
func (*ContractSpec) ProtoMessage()               {}
func (*ContractSpec) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *ContractSpec) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *ContractSpec) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ContractSpec) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type TxHeader struct {
	Version    uint32          `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	CreateTime uint32          `protobuf:"varint,2,opt,name=createTime" json:"createTime,omitempty"`
	Nonce      uint32          `protobuf:"varint,3,opt,name=nonce" json:"nonce,omitempty"`
	Type       TransactionType `protobuf:"varint,4,opt,name=type,enum=proto.TransactionType" json:"type,omitempty"`
}

func (m *TxHeader) Reset()                    { *m = TxHeader{} }
func (m *TxHeader) String() string            { return proto1.CompactTextString(m) }
func (*TxHeader) ProtoMessage()               {}
func (*TxHeader) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *TxHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TxHeader) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *TxHeader) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TxHeader) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_Issue
}

type Transaction struct {
	Header       *TxHeader     `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Inputs       []*TxIn       `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty"`
	Outputs      []*TxOut      `protobuf:"bytes,3,rep,name=outputs" json:"outputs,omitempty"`
	ContractSpec *ContractSpec `protobuf:"bytes,4,opt,name=contractSpec" json:"contractSpec,omitempty"`
	Payload      []byte        `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto1.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *Transaction) GetHeader() *TxHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Transaction) GetInputs() []*TxIn {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Transaction) GetOutputs() []*TxOut {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Transaction) GetContractSpec() *ContractSpec {
	if m != nil {
		return m.ContractSpec
	}
	return nil
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto1.RegisterType((*OutPoint)(nil), "proto.OutPoint")
	proto1.RegisterType((*TxIn)(nil), "proto.TxIn")
	proto1.RegisterType((*TxOut)(nil), "proto.TxOut")
	proto1.RegisterType((*ContractSpec)(nil), "proto.ContractSpec")
	proto1.RegisterType((*TxHeader)(nil), "proto.TxHeader")
	proto1.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto1.RegisterEnum("proto.TransactionType", TransactionType_name, TransactionType_value)
}

func init() { proto1.RegisterFile("transaction.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0x1d, 0xbb, 0xcd, 0xd8, 0x69, 0xdc, 0x29, 0xaa, 0x7c, 0x40, 0x28, 0x32, 0x12,
	0x44, 0x3d, 0x54, 0x22, 0x3d, 0xc0, 0x15, 0x71, 0x69, 0x10, 0x22, 0xb0, 0x35, 0x42, 0x1c, 0x17,
	0x7b, 0x24, 0x2c, 0x9a, 0x5d, 0x6b, 0x3d, 0x8e, 0x9c, 0x17, 0x40, 0xe2, 0x05, 0x79, 0x9e, 0xca,
	0x6b, 0x3b, 0x7f, 0x7a, 0xf2, 0x7e, 0xdf, 0xfc, 0x76, 0x76, 0xe6, 0x33, 0x5c, 0xb0, 0x91, 0xaa,
	0x92, 0x19, 0x17, 0x5a, 0xdd, 0x94, 0x46, 0xb3, 0x46, 0xcf, 0x7e, 0x92, 0xf7, 0x70, 0xb6, 0xaa,
	0xf9, 0xab, 0x2e, 0x14, 0xe3, 0x15, 0xf8, 0xdc, 0xdc, 0xc9, 0xea, 0x77, 0xec, 0xcc, 0x9c, 0x79,
	0x28, 0x7a, 0x85, 0xcf, 0xc1, 0x2b, 0x54, 0x4e, 0x4d, 0x7c, 0x32, 0x73, 0xe6, 0x13, 0xd1, 0x89,
	0xe4, 0x27, 0x8c, 0xd2, 0x66, 0xa9, 0xf0, 0x16, 0xc2, 0xd2, 0xd0, 0x66, 0xe8, 0x62, 0xef, 0x06,
	0x8b, 0x69, 0xf7, 0xcc, 0xcd, 0x60, 0x8b, 0x23, 0x08, 0x5f, 0xc0, 0x98, 0x9b, 0x1f, 0x05, 0x2b,
	0xaa, 0x2a, 0xdb, 0x36, 0x14, 0x7b, 0x23, 0x79, 0x0b, 0x5e, 0xda, 0xac, 0x6a, 0x6e, 0x5f, 0xde,
	0xc8, 0x87, 0x9a, 0x6c, 0x53, 0x57, 0x74, 0x02, 0x11, 0x46, 0x32, 0xcf, 0x4d, 0x7f, 0xcf, 0x9e,
	0x93, 0x2f, 0x10, 0x7e, 0xd4, 0x8a, 0x8d, 0xcc, 0xf8, 0xbe, 0xa4, 0x6c, 0xc7, 0x38, 0x7b, 0xa6,
	0xf5, 0x32, 0x9d, 0xd3, 0x70, 0xaf, 0x3d, 0xb7, 0x3b, 0x97, 0xd2, 0xc8, 0x75, 0x15, 0xbb, 0x33,
	0x77, 0x3e, 0x16, 0xbd, 0x4a, 0xfe, 0x3a, 0x70, 0x96, 0x36, 0x77, 0x24, 0x73, 0x32, 0x18, 0xc3,
	0xe9, 0x86, 0x4c, 0x55, 0x68, 0x65, 0xfb, 0x4d, 0xc4, 0x20, 0xf1, 0x25, 0x40, 0x66, 0x48, 0x32,
	0xa5, 0xc5, 0x9a, 0xfa, 0x7c, 0x0e, 0x9c, 0x76, 0x01, 0xa5, 0x55, 0x46, 0xb1, 0xdb, 0x45, 0x67,
	0x05, 0x5e, 0xc3, 0x88, 0xb7, 0x25, 0xc5, 0xa3, 0x99, 0x33, 0x3f, 0x5f, 0x5c, 0xf5, 0x51, 0xa5,
	0xfb, 0x7f, 0x94, 0x6e, 0x4b, 0x12, 0x96, 0x49, 0xfe, 0x3b, 0x10, 0x1c, 0x54, 0xf0, 0x0d, 0xf8,
	0xdd, 0x54, 0x4f, 0x82, 0x1e, 0x86, 0x15, 0x7d, 0x19, 0x5f, 0x81, 0x5f, 0xa8, 0xb2, 0xe6, 0x36,
	0x5f, 0x77, 0x1e, 0x2c, 0x82, 0x1d, 0xb8, 0x54, 0xa2, 0x2f, 0xe1, 0x6b, 0x38, 0xd5, 0x35, 0x5b,
	0xca, 0xb5, 0x54, 0xb8, 0xa3, 0x56, 0x35, 0x8b, 0xa1, 0x88, 0xef, 0x20, 0xcc, 0x0e, 0xe2, 0xb5,
	0x93, 0x07, 0x8b, 0xcb, 0x1e, 0x3e, 0x4c, 0x5e, 0x1c, 0x81, 0x6d, 0x74, 0xa5, 0xdc, 0x3e, 0x68,
	0x99, 0xc7, 0x9e, 0x8d, 0x7d, 0x90, 0xd7, 0xff, 0x1c, 0x98, 0x3e, 0x59, 0x19, 0xc7, 0xe0, 0x2d,
	0xab, 0xaa, 0xa6, 0xe8, 0x19, 0x4e, 0x21, 0xb0, 0xc7, 0xef, 0x65, 0x2e, 0x99, 0x22, 0x07, 0x01,
	0xfc, 0x0f, 0xac, 0xd7, 0x45, 0x16, 0x9d, 0x20, 0xc2, 0xf9, 0xa7, 0xfb, 0xe1, 0xd5, 0xa5, 0x2a,
	0x38, 0x72, 0xf1, 0x12, 0xa6, 0x9f, 0x6b, 0x79, 0x64, 0x8e, 0x5a, 0x70, 0xef, 0x6c, 0xf4, 0x1f,
	0x8a, 0x3c, 0xbc, 0x80, 0xc9, 0xe0, 0x7d, 0xab, 0xc9, 0x6c, 0x23, 0xff, 0x97, 0x6f, 0xf7, 0xb8,
	0x7d, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x0f, 0x95, 0x92, 0x28, 0x03, 0x00, 0x00,
}
